import type { Meta, StoryObj } from "@storybook/react-vite";
import { Icons } from "./Icons";

const meta: Meta<typeof Icons> = {
  title: "Components/Icons",
  component: Icons,
  tags: ["autodocs"],

  argTypes: {
    icon: {
      options: [
        "alert-triangle",
        "annotation-info",
        "announcement-01",
        "arrow-down",
        "arrow-left",
        "arrow-narrow-down-right",
        "arrow-narrow-up-right",
        "arrow-right",
        "arrow-up",
        "bank",
        "bell-01",
        "briefcase-01",
        "building-07",
        "calendar",
        "check",
        "check-circle",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "clock",
        "clock-rewind",
        "code-snippet-02",
        "copy-01",
        "dots-grid",
        "dots-horizontal",
        "download-02",
        "drag-drop",
        "edit-02",
        "expand-02",
        "eye",
        "eye-off",
        "file-05",
        "file-attachment-02",
        "filter-lines",
        "flag-01",
        "folder",
        "headphones-01",
        "heart",
        "help-circle",
        "home",
        "home-03",
        "icon-90",
        "info-circle",
        "laptop-01",
        "link-01",
        "list",
        "lock-01",
        "log-in-02",
        "log-out-02",
        "luggage-02",
        "mail-01",
        "map-01",
        "mark",
        "marker-pin-01",
        "marker-pin-06",
        "menu-01",
        "microphone-01",
        "microphone-off-01",
        "minus",
        "monitor-04",
        "navigation-pointer-01",
        "phone-02",
        "pin-02",
        "play",
        "plus",
        "power-01",
        "recording-01",
        "refresh-ccw-05",
        "route",
        "rss-01",
        "save-01",
        "search-md",
        "send-01",
        "settings-01",
        "settings-04",
        "share-07",
        "star-01",
        "switch-horizontal-01",
        "switch-vertical-01",
        "terminal",
        "trash",
        "upload-02",
        "user-01",
        "users-01",
        "volume-max",
        "volume-min",
        "volume-x",
        "x-close",
      ],
      control: { type: "select" },
    },
    iconMap: { control: { type: "text" } },
  },
};

export default meta;

type Story = StoryObj<typeof Icons>;

export const Default: Story = {
  args: {
    icon: "search-md",
    className: "",
    iconMap: "https://c.animaapp.com/moieyt2ccA1Ry9/img/icon-map-01-1_1.svg",
  },
};

export const IconAlertTriangle: Story = {
  args: {
    icon: "alert-triangle",
    className: "",
    iconMap: "https://c.animaapp.com/moieyt2ccA1Ry9/img/icon-map-01-1_1.svg",
  },
};

export const IconAnnotationInfo: Story = {
  args: {
    icon: "annotation-info",
    className: "",
    iconMap: "https://c.animaapp.com/moieyt2ccA1Ry9/img/icon-map-01-1_1.svg",
  },
};
